name             = Dist-Zilla-App-Command-versions
author           = Mikko Koivunalho <mikkoi@cpan.org>
license          = Perl_5
copyright_holder = Mikko Koivunalho
copyright_year   = 2026
main_module      = lib/Dist/Zilla/App/Command/versions.pm

[Meta::Contributors]

[MetaResources]
homepage            = https://metacpan.org/release/Dist-Zilla-App-Command-versions
bugtracker.web      = https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-App-Command-versions
bugtracker.mailto   = bug-Dist-Zilla-App-Command-versions@rt.cpan.org
repository.url      = git://github.com/mikkoi/dist-zilla-app-command-versions.git
repository.web      = https://github.com/mikkoi/dist-zilla-app-command-versions
repository.type     = git

[Keywords]
keywords = perl5

[@MIKKOI]

[Software::Policies / License]
policy_attribute = perl_5_double_license = true

[Software::Policies / Contributing]

[Software::Policies / CodeOfConduct]
class = ContributorCovenant
version = 2.1

[Software::Policies / Security]
policy_attribute = url = https://github.com/mikkoi/dist-zilla-app-command-versions/blob/main/SECURITY.md
policy_attribute = timeframe = 14 days
policy_attribute = perl_support_years = 10

[Prereqs / DevelopSuggests]
Dist::Zilla::App::Command::podpreview = 0.004
App::RewriteVersion = 1.000

[Prereqs / TestRecommends]
Carp::Always = 0

[Prereqs / RuntimeRequires]
perl = 5.014

[Prereqs / RuntimeRecommends]
Dist::Zilla::Plugin::VersionsVersionProvider = 0

; After release
[BumpVersionAfterRelease]

; commit source files after modification
[Git::Commit / CommitAfterBumpVersionAfterRelease] ; commit Changes (for new dev)
allow_dirty_match = (^lib/|^script/)
commit_msg = Bump version
